// SPDX-License-Identifier: MIT

/* AUTOGENERATED FILE BY HARDHAT-ZKIT. DO NOT EDIT. */

pragma solidity >=0.7.0 <0.9.0;

contract ConfidentialApproveCircuitGroth16Verifier {
    // @dev scalar field size
    uint256 public constant SCALAR_FIELD_SIZE =
        21888242871839275222246405745257275088548364400416034343698204186575808495617;
    /// @dev base field size
    uint256 public constant BASE_FIELD_SIZE =
        21888242871839275222246405745257275088696311157297823662689037894645226208583;

    /// @dev verification key data
    uint256 public constant ALPHA_X =
        20491192805390485299153009773594534940189261866228447918068658471970481763042;
    uint256 public constant ALPHA_Y =
        9383485363053290200918347156157836566562967994039712273449902621266178545958;
    uint256 public constant BETA_X1 =
        4252822878758300859123897981450591353533073413197771768651442665752259397132;
    uint256 public constant BETA_X2 =
        6375614351688725206403948262868962793625744043794305715222011528459656738731;
    uint256 public constant BETA_Y1 =
        21847035105528745403288232691147584728191162732299865338377159692350059136679;
    uint256 public constant BETA_Y2 =
        10505242626370262277552901082094356697409835680220590971873171140371331206856;
    uint256 public constant GAMMA_X1 =
        11559732032986387107991004021392285783925812861821192530917403151452391805634;
    uint256 public constant GAMMA_X2 =
        10857046999023057135944570762232829481370756359578518086990519993285655852781;
    uint256 public constant GAMMA_Y1 =
        4082367875863433681332203403145435568316851327593401208105741076214120093531;
    uint256 public constant GAMMA_Y2 =
        8495653923123431417604973247489272438418190587263600148770280649306958101930;
    uint256 public constant DELTA_X1 =
        11559732032986387107991004021392285783925812861821192530917403151452391805634;
    uint256 public constant DELTA_X2 =
        10857046999023057135944570762232829481370756359578518086990519993285655852781;
    uint256 public constant DELTA_Y1 =
        4082367875863433681332203403145435568316851327593401208105741076214120093531;
    uint256 public constant DELTA_Y2 =
        8495653923123431417604973247489272438418190587263600148770280649306958101930;

    uint256 public constant IC0_X =
        12419509356497170638113332059537322719674610186362646649625863175226932529095;
    uint256 public constant IC0_Y =
        4439958828296840320090291897318978161568466925463584279183908619322449678672;
    uint256 public constant IC1_X =
        12502670031244960413111633815886672570814075189952787896355999707750139199637;
    uint256 public constant IC1_Y =
        2230115862652285089805685624568347854195542460586151887320873722489274106634;
    uint256 public constant IC2_X =
        15203710230452416574451073139011426761558024715334151011751421779500086773275;
    uint256 public constant IC2_Y =
        12735004765538293266789337904488848327751036283523855150399561579258970279968;
    uint256 public constant IC3_X =
        18112154457624540733453242064470868956771573725910652528368367535912340744811;
    uint256 public constant IC3_Y =
        14531173789374549914071994278877761787052741891880416757813405002443625955813;
    uint256 public constant IC4_X =
        10931404981101608124047132331056556239125012667592532493208366785743941528983;
    uint256 public constant IC4_Y =
        4561137895612327114510097867908686635122289369386923699855934671931385681599;
    uint256 public constant IC5_X =
        11167789746878189731995600925616907208718427623161918539919187238644314583513;
    uint256 public constant IC5_Y =
        11508229663947051067095094059284333179715292660513743487312450753006147186150;
    uint256 public constant IC6_X =
        9111328823455268233944260814823392673379433881764951148600327821201746526349;
    uint256 public constant IC6_Y =
        15876717505544332348342383516432815830210827675092596307084711009745412196237;
    uint256 public constant IC7_X =
        3183652087459301610116980681393495443515209166689171680459924610495473905512;
    uint256 public constant IC7_Y =
        1888602434198340756023158104193942519523238589318116307181157676255308116535;
    uint256 public constant IC8_X =
        4169618424520028114807448558674344400756782388742569207036853524560334269341;
    uint256 public constant IC8_Y =
        18131950852879493577186452382797519380364980255017192752560944321663278521716;
    uint256 public constant IC9_X =
        16841556592694799736561564564000858068217538333323163353902520169723942346273;
    uint256 public constant IC9_Y =
        2207665045729895680707666952738478309382466070950764924720971017599292252346;
    uint256 public constant IC10_X =
        18067643825098209854555209569941781201901926591483865021723621721887817609263;
    uint256 public constant IC10_Y =
        17097254029327391248065609296508172893074217819620636029409408660930065056884;
    uint256 public constant IC11_X =
        10925942330814779156750948666517035500382299846321347238801448325085864141411;
    uint256 public constant IC11_Y =
        20314746007305736600922622723508614750907969730059468122908823908092536239217;
    uint256 public constant IC12_X =
        9634018202406914925706656185811403062710217853242990684924606787873004572712;
    uint256 public constant IC12_Y =
        19114675970968169890094116600894730264825296102356360175981312804119802038298;
    uint256 public constant IC13_X =
        2488872248164544654006661225921806497155510721166521573150496680084556241644;
    uint256 public constant IC13_Y =
        6707721947227923237982156296615631115240863637738236851020433970404087411390;
    uint256 public constant IC14_X =
        21882645832997923637229913915504457668378326221954374076501007667599781158443;
    uint256 public constant IC14_Y =
        19222092217450584492563812590501687371013768350176080264135935713844803181311;
    uint256 public constant IC15_X =
        14046026330060990212390351667625169820985850346590814746640987692074181688354;
    uint256 public constant IC15_Y =
        1485873580870328740016871892448801100826492660645902896117694637215421824224;
    uint256 public constant IC16_X =
        16921679191647074383642520681426429196193590753323994669083070881808366277914;
    uint256 public constant IC16_Y =
        3981703646466904478700962430060063890093817449196604359475021869050326085287;
    uint256 public constant IC17_X =
        5096019379957928172374038523873181317921253861168455566708511071196325933842;
    uint256 public constant IC17_Y =
        14913711313564082044751142290138949888299099773219688283565010646841788376636;
    uint256 public constant IC18_X =
        8218234445704207527327369496915628005854277300825402826654793850814659783882;
    uint256 public constant IC18_Y =
        17017589223255685412557354487020409811839627505853423368933320672128269764027;
    uint256 public constant IC19_X =
        12367048909882192241778707008859578196577273910011797295901578498653257925424;
    uint256 public constant IC19_Y =
        13291460105625347027253784641876483364297252951787595992567574672356661160190;
    uint256 public constant IC20_X =
        14153914838710086556632546735939213811309929547306737232085898301269770515420;
    uint256 public constant IC20_Y =
        15669526630628535213264590026599293870917189339828766167235742959813731992913;
    uint256 public constant IC21_X =
        19653061892120200687016990994042955600463917635073561984276990902837555927028;
    uint256 public constant IC21_Y =
        9014362164839562061361306384026502822736866202765829666830538825259916010950;
    uint256 public constant IC22_X =
        14912031427558864928936514890250509894655680339098177968656831076463945008161;
    uint256 public constant IC22_Y =
        6991045610044103084118430799876670183999852769009917955777342286551441481638;
    uint256 public constant IC23_X =
        19683148470927536879711562646642734651404656099542925696876945016082163794923;
    uint256 public constant IC23_Y =
        17877868143867005826348215313821864982899084768601841617662932270706061752634;
    uint256 public constant IC24_X =
        9050447794332249206531324860833378442586653574892214987749017510395402153651;
    uint256 public constant IC24_Y =
        17241685880898875693271735031080340005110365626006559002589818614678223433118;
    uint256 public constant IC25_X =
        8332015525279012749932497362676148211126321517970776830828492173981518341116;
    uint256 public constant IC25_Y =
        6820121898977708859297476440882599920965067950595550190631075790913456749661;
    uint256 public constant IC26_X =
        17443233006259185009917880799948664041992333704720014812351640611229179706358;
    uint256 public constant IC26_Y =
        19682374023891995978609466674740309934926195908616367714891029089407585260203;
    uint256 public constant IC27_X =
        9499233577369290138280014191501642153759579232479050400398464976341565191885;
    uint256 public constant IC27_Y =
        6784348804170584361316938409366905742833023324670289581494715570294022062849;
    uint256 public constant IC28_X =
        8583058845372386903064715835182487748326910262659985586932130655979068544376;
    uint256 public constant IC28_Y =
        263212049098869777757785648648008746500976543088813285760573890510389005732;
    uint256 public constant IC29_X =
        19023881493049372401384232678650154198109537309822867760409361381783109166002;
    uint256 public constant IC29_Y =
        20671899181205838579828805746085866521731048275542101693659468939606348427562;
    uint256 public constant IC30_X =
        6556457014235343084546397898590673545517879082861182991995802525955412246646;
    uint256 public constant IC30_Y =
        13971768365163445149672591515527869805335835689213214002099509021363649029723;
    
    /// @dev memory pointer sizes
    uint16 public constant P_PUBLIC_SIGNALS_ACCUMULATOR_SIZE = 128;
    uint16 public constant P_TOTAL_SIZE = 896;

    function verifyProof(
        uint256[2] memory pointA_,
        uint256[2][2] memory pointB_,
        uint256[2] memory pointC_,
        uint256[30] memory publicSignals_
    ) public view returns (bool verified_) {
        assembly {
            function checkField(signal_) -> res_ {
                res_ := lt(signal_, SCALAR_FIELD_SIZE)
            }

            function g1MulAdd(pR_, x_, y_, s_) -> res_ {
                let pointer_ := mload(64) // free pointer

                mstore(pointer_, x_)
                mstore(add(pointer_, 32), y_)
                mstore(add(pointer_, 64), s_)

                res_ := staticcall(6000, 7, pointer_, 96, pointer_, 64) // ecMul
                res_ := and(res_, gt(returndatasize(), 0)) // check that multiplication succeeded

                if iszero(res_) {
                    leave
                }

                mstore(add(pointer_, 64), mload(pR_))
                mstore(add(pointer_, 96), mload(add(pR_, 32)))

                res_ := staticcall(150, 6, pointer_, 128, pR_, 64) // ecAdd
                res_ := and(res_, gt(returndatasize(), 0)) // check that addition succeeded
            }

            function checkPairing(pA_, pB_, pC_, pubSignals_, pointer_) -> res_ {
                let pPairing_ := add(pointer_, P_PUBLIC_SIGNALS_ACCUMULATOR_SIZE)

                mstore(pointer_, IC0_X)
                mstore(add(pointer_, 32), IC0_Y)

                /// @dev compute the linear combination of public signals
                if iszero(g1MulAdd(pointer_, IC1_X, IC1_Y, mload(add(pubSignals_, 0)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC2_X, IC2_Y, mload(add(pubSignals_, 32)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC3_X, IC3_Y, mload(add(pubSignals_, 64)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC4_X, IC4_Y, mload(add(pubSignals_, 96)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC5_X, IC5_Y, mload(add(pubSignals_, 128)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC6_X, IC6_Y, mload(add(pubSignals_, 160)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC7_X, IC7_Y, mload(add(pubSignals_, 192)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC8_X, IC8_Y, mload(add(pubSignals_, 224)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC9_X, IC9_Y, mload(add(pubSignals_, 256)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC10_X, IC10_Y, mload(add(pubSignals_, 288)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC11_X, IC11_Y, mload(add(pubSignals_, 320)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC12_X, IC12_Y, mload(add(pubSignals_, 352)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC13_X, IC13_Y, mload(add(pubSignals_, 384)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC14_X, IC14_Y, mload(add(pubSignals_, 416)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC15_X, IC15_Y, mload(add(pubSignals_, 448)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC16_X, IC16_Y, mload(add(pubSignals_, 480)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC17_X, IC17_Y, mload(add(pubSignals_, 512)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC18_X, IC18_Y, mload(add(pubSignals_, 544)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC19_X, IC19_Y, mload(add(pubSignals_, 576)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC20_X, IC20_Y, mload(add(pubSignals_, 608)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC21_X, IC21_Y, mload(add(pubSignals_, 640)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC22_X, IC22_Y, mload(add(pubSignals_, 672)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC23_X, IC23_Y, mload(add(pubSignals_, 704)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC24_X, IC24_Y, mload(add(pubSignals_, 736)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC25_X, IC25_Y, mload(add(pubSignals_, 768)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC26_X, IC26_Y, mload(add(pubSignals_, 800)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC27_X, IC27_Y, mload(add(pubSignals_, 832)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC28_X, IC28_Y, mload(add(pubSignals_, 864)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC29_X, IC29_Y, mload(add(pubSignals_, 896)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC30_X, IC30_Y, mload(add(pubSignals_, 928)))) {
                    leave
                }
                
                /// @dev -A
                mstore(pPairing_, mload(pA_))
                mstore(
                    add(pPairing_, 32),
                    mod(sub(BASE_FIELD_SIZE, mload(add(pA_, 32))), BASE_FIELD_SIZE)
                )

                /// @dev B
                mstore(add(pPairing_, 64), mload(mload(pB_)))
                mstore(add(pPairing_, 96), mload(add(mload(pB_), 32)))
                mstore(add(pPairing_, 128), mload(mload(add(pB_, 32))))
                mstore(add(pPairing_, 160), mload(add(mload(add(pB_, 32)), 32)))

                /// @dev alpha1
                mstore(add(pPairing_, 192), ALPHA_X)
                mstore(add(pPairing_, 224), ALPHA_Y)

                /// @dev beta2
                mstore(add(pPairing_, 256), BETA_X1)
                mstore(add(pPairing_, 288), BETA_X2)
                mstore(add(pPairing_, 320), BETA_Y1)
                mstore(add(pPairing_, 352), BETA_Y2)

                /// @dev public signals
                mstore(add(pPairing_, 384), mload(pointer_))
                mstore(add(pPairing_, 416), mload(add(pointer_, 32)))

                /// @dev gamma2
                mstore(add(pPairing_, 448), GAMMA_X1)
                mstore(add(pPairing_, 480), GAMMA_X2)
                mstore(add(pPairing_, 512), GAMMA_Y1)
                mstore(add(pPairing_, 544), GAMMA_Y2)

                /// @dev C
                mstore(add(pPairing_, 576), mload(pC_))
                mstore(add(pPairing_, 608), mload(add(pC_, 32)))

                /// @dev delta2
                mstore(add(pPairing_, 640), DELTA_X1)
                mstore(add(pPairing_, 672), DELTA_X2)
                mstore(add(pPairing_, 704), DELTA_Y1)
                mstore(add(pPairing_, 736), DELTA_Y2)

                res_ := staticcall(181000, 8, pPairing_, 768, pPairing_, 32) // ecPairing
                res_ := and(res_, mload(pPairing_)) // check that pairing succeeded
            }

            let pointer_ := mload(64) // free pointer
            mstore(64, add(pointer_, P_TOTAL_SIZE))

            /// @dev check that all public signals are in F
            verified_ := 1
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 0))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 32))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 64))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 96))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 128))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 160))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 192))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 224))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 256))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 288))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 320))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 352))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 384))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 416))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 448))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 480))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 512))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 544))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 576))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 608))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 640))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 672))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 704))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 736))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 768))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 800))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 832))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 864))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 896))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 928))))
            
            /// @dev check pairings
            if not(iszero(verified_)) {
                verified_ := checkPairing(pointA_, pointB_, pointC_, publicSignals_, pointer_)
            }
        }
    }
}
