// SPDX-License-Identifier: MIT

/* AUTOGENERATED FILE BY HARDHAT-ZKIT. DO NOT EDIT. */

pragma solidity >=0.7.0 <0.9.0;

contract ConfidentialTransferFromCircuitGroth16Verifier {
    // @dev scalar field size
    uint256 public constant SCALAR_FIELD_SIZE =
        21888242871839275222246405745257275088548364400416034343698204186575808495617;
    /// @dev base field size
    uint256 public constant BASE_FIELD_SIZE =
        21888242871839275222246405745257275088696311157297823662689037894645226208583;

    /// @dev verification key data
    uint256 public constant ALPHA_X =
        20491192805390485299153009773594534940189261866228447918068658471970481763042;
    uint256 public constant ALPHA_Y =
        9383485363053290200918347156157836566562967994039712273449902621266178545958;
    uint256 public constant BETA_X1 =
        4252822878758300859123897981450591353533073413197771768651442665752259397132;
    uint256 public constant BETA_X2 =
        6375614351688725206403948262868962793625744043794305715222011528459656738731;
    uint256 public constant BETA_Y1 =
        21847035105528745403288232691147584728191162732299865338377159692350059136679;
    uint256 public constant BETA_Y2 =
        10505242626370262277552901082094356697409835680220590971873171140371331206856;
    uint256 public constant GAMMA_X1 =
        11559732032986387107991004021392285783925812861821192530917403151452391805634;
    uint256 public constant GAMMA_X2 =
        10857046999023057135944570762232829481370756359578518086990519993285655852781;
    uint256 public constant GAMMA_Y1 =
        4082367875863433681332203403145435568316851327593401208105741076214120093531;
    uint256 public constant GAMMA_Y2 =
        8495653923123431417604973247489272438418190587263600148770280649306958101930;
    uint256 public constant DELTA_X1 =
        11559732032986387107991004021392285783925812861821192530917403151452391805634;
    uint256 public constant DELTA_X2 =
        10857046999023057135944570762232829481370756359578518086990519993285655852781;
    uint256 public constant DELTA_Y1 =
        4082367875863433681332203403145435568316851327593401208105741076214120093531;
    uint256 public constant DELTA_Y2 =
        8495653923123431417604973247489272438418190587263600148770280649306958101930;

    uint256 public constant IC0_X =
        19735339103349976248830173399070170674975666429471535995725775243409265073881;
    uint256 public constant IC0_Y =
        21880003610767097015458466055923389081879633241485010111901293473768190286666;
    uint256 public constant IC1_X =
        4642252772980736365784392765734251512260794406145217446669327606668550585577;
    uint256 public constant IC1_Y =
        10527167149476088413503600396220289122085803551947191387142593790647252113451;
    uint256 public constant IC2_X =
        7815067360069755846204903392827202201978745104158264758531824753148856214453;
    uint256 public constant IC2_Y =
        6871605668499558036283766083156785349709179411194088082634778116052677570299;
    uint256 public constant IC3_X =
        15252707154029451095006571058189936200413424193018242102576106325404017429728;
    uint256 public constant IC3_Y =
        18477907295008433430975506054906623369900340012262877770275526585197302462755;
    uint256 public constant IC4_X =
        21460408146218759851794357548380184685681221387714846198291550240996255625995;
    uint256 public constant IC4_Y =
        689326289683019746025083235223710961287365753991331805300640637548006504941;
    uint256 public constant IC5_X =
        2717403638639596328385405237649721994833594011768401392348290450477232598000;
    uint256 public constant IC5_Y =
        16601415850462804019852577240501583556167364366085447541726993333551836641509;
    uint256 public constant IC6_X =
        12113515326677254508117854345514012589850831243378639710727111693400370632931;
    uint256 public constant IC6_Y =
        7144376562029571196961405150882117904320621439198872195639601632562253711303;
    uint256 public constant IC7_X =
        20927725799573936412198562114262987326917144712500662466776297018461749186791;
    uint256 public constant IC7_Y =
        679325313180140797492088851350314752247377156861322781122536676409312820336;
    uint256 public constant IC8_X =
        13623028358146057514063462017274696862329115283890415315817490720236826086647;
    uint256 public constant IC8_Y =
        3960036647063347258074148917773447753216754198331302235943102247081658759631;
    uint256 public constant IC9_X =
        565556738142480600285470522715467689487076807277557824800730076998258485474;
    uint256 public constant IC9_Y =
        13727050173960883921084554795513146278389772011356772441592148671845374344439;
    uint256 public constant IC10_X =
        2619939645126196781904178535753211327050465027295451080336825267160767306026;
    uint256 public constant IC10_Y =
        2447073741101125805553938604264506433507653726212727556984049659865825442327;
    uint256 public constant IC11_X =
        9984756251327792819366658785728999113172638207769329283700408717436930926455;
    uint256 public constant IC11_Y =
        12737279539162800622428600615172508907477351466800309363654241196768806426680;
    uint256 public constant IC12_X =
        1820885668273827619665366372418133562136635091032419238178281522678462051102;
    uint256 public constant IC12_Y =
        19783163517093021741096878448414157970795249370022930713576468985204933259383;
    uint256 public constant IC13_X =
        8965110189830744240199244666046040045814862059527139411431695808298428856579;
    uint256 public constant IC13_Y =
        15830705752011087535415159393665114002512652856723718901685260922384740152986;
    uint256 public constant IC14_X =
        19120918230968070823037957719696120651772183962655817801408999610791439114679;
    uint256 public constant IC14_Y =
        9772143074871509440183266652282377014980124454536202630680306680572684547654;
    uint256 public constant IC15_X =
        8751801901003192583471094879571133665217438812462281119472747206167616507235;
    uint256 public constant IC15_Y =
        5819112873650349329266229268132718146966543962273194071837695840766335190849;
    uint256 public constant IC16_X =
        12072492230436290687309830426664628520620222013203587070471415474269293645077;
    uint256 public constant IC16_Y =
        17456811083474084812700049973993856266759743888919281922574433655370767113541;
    uint256 public constant IC17_X =
        16676074854388347388209847868866873736466436011931727233293137893474313216113;
    uint256 public constant IC17_Y =
        7157393631342744063022108836939521393017968982724814691276192787653075987000;
    uint256 public constant IC18_X =
        2948272896710638291888559576667650066527448582657011839007594218148224535551;
    uint256 public constant IC18_Y =
        13214632186736577559001746006251814421341244161564718337851868254366940548036;
    uint256 public constant IC19_X =
        19196796891501168567733936398895656529707456544885276188691744998168589523260;
    uint256 public constant IC19_Y =
        17465156749015255501969146013551551985326816980885818180047256000331630568251;
    uint256 public constant IC20_X =
        20893641019131981229902980825511379488993644655758942132639319230406478862044;
    uint256 public constant IC20_Y =
        10901269342340436325105738259994359138462938958904777042036570607758656276824;
    uint256 public constant IC21_X =
        10145335900611310270113716974775790013535305135177167008784564376941745794004;
    uint256 public constant IC21_Y =
        1558454315921559929883896348771665026016375193547301978112307868742992861054;
    uint256 public constant IC22_X =
        8291580063207494901935637674725082836163119265746297545307406557554945173076;
    uint256 public constant IC22_Y =
        20864308360358882968241864674594015018069891685037621520160781488288520896319;
    uint256 public constant IC23_X =
        18563377508936591113075418645615294038936001189571664022083689802864794395081;
    uint256 public constant IC23_Y =
        14751031111586959077590105452298298846835607914184517588731365615456666077702;
    uint256 public constant IC24_X =
        10303645280073579708653051098521046247538698644798975038992601898031073451109;
    uint256 public constant IC24_Y =
        2786643741306232186142059236681544839023190273469879681687971959561487044474;
    uint256 public constant IC25_X =
        12841514080263724577158282909137301802771098456641443509212348948809116509990;
    uint256 public constant IC25_Y =
        9585146156266024194311842754060755725256656273995569903022230005811570170033;
    uint256 public constant IC26_X =
        5268438852698712096249144419760483776953264811979518577876938847161657424017;
    uint256 public constant IC26_Y =
        7991210130580610953500103627701885081962768313587743282862756905211409125624;
    uint256 public constant IC27_X =
        11053596336154868343075007192383639660182196418452746832362855001949980845430;
    uint256 public constant IC27_Y =
        10095066215022037090632262648483052289863029646772119522794919222494740363561;
    uint256 public constant IC28_X =
        1279952847298564580219250274483038488305984820700990207600071594486165371554;
    uint256 public constant IC28_Y =
        11919361179998518535680707339645915951346269373235369905963028972957884924958;
    uint256 public constant IC29_X =
        21295884226904551343485715402867757324864132326434490347561417159962395927588;
    uint256 public constant IC29_Y =
        3340192726568497194718504619844659288507718899631660470197042695473112703236;
    uint256 public constant IC30_X =
        7527852580407790046340758977667030964799171065087845353890495398326504936274;
    uint256 public constant IC30_Y =
        8573521347911466050836282479105461921670810249959098451767705159456580987196;
    uint256 public constant IC31_X =
        9118227253308340503846522150485069650258214361227319734663895373771348077855;
    uint256 public constant IC31_Y =
        20749088203277079874694100280753646092833409130077908963558987991864504725091;
    uint256 public constant IC32_X =
        13682957368500827950282289150757996985910916774771217758295378933681125035696;
    uint256 public constant IC32_Y =
        3681589484624450152837766957049181243143942868193049233941529019133190440127;
    uint256 public constant IC33_X =
        18216906615484412010661807448876817102837700927213587688057601469182294889594;
    uint256 public constant IC33_Y =
        11063777809757249742075805732187924910878146883790380600166474970749910822189;
    uint256 public constant IC34_X =
        8864301910555020431308109218081119402670095737363066191337418266977207237331;
    uint256 public constant IC34_Y =
        8381998542732299345510934008184237423797981402544045462049178411300149555722;
    
    /// @dev memory pointer sizes
    uint16 public constant P_PUBLIC_SIGNALS_ACCUMULATOR_SIZE = 128;
    uint16 public constant P_TOTAL_SIZE = 896;

    function verifyProof(
        uint256[2] memory pointA_,
        uint256[2][2] memory pointB_,
        uint256[2] memory pointC_,
        uint256[34] memory publicSignals_
    ) public view returns (bool verified_) {
        assembly {
            function checkField(signal_) -> res_ {
                res_ := lt(signal_, SCALAR_FIELD_SIZE)
            }

            function g1MulAdd(pR_, x_, y_, s_) -> res_ {
                let pointer_ := mload(64) // free pointer

                mstore(pointer_, x_)
                mstore(add(pointer_, 32), y_)
                mstore(add(pointer_, 64), s_)

                res_ := staticcall(6000, 7, pointer_, 96, pointer_, 64) // ecMul
                res_ := and(res_, gt(returndatasize(), 0)) // check that multiplication succeeded

                if iszero(res_) {
                    leave
                }

                mstore(add(pointer_, 64), mload(pR_))
                mstore(add(pointer_, 96), mload(add(pR_, 32)))

                res_ := staticcall(150, 6, pointer_, 128, pR_, 64) // ecAdd
                res_ := and(res_, gt(returndatasize(), 0)) // check that addition succeeded
            }

            function checkPairing(pA_, pB_, pC_, pubSignals_, pointer_) -> res_ {
                let pPairing_ := add(pointer_, P_PUBLIC_SIGNALS_ACCUMULATOR_SIZE)

                mstore(pointer_, IC0_X)
                mstore(add(pointer_, 32), IC0_Y)

                /// @dev compute the linear combination of public signals
                if iszero(g1MulAdd(pointer_, IC1_X, IC1_Y, mload(add(pubSignals_, 0)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC2_X, IC2_Y, mload(add(pubSignals_, 32)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC3_X, IC3_Y, mload(add(pubSignals_, 64)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC4_X, IC4_Y, mload(add(pubSignals_, 96)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC5_X, IC5_Y, mload(add(pubSignals_, 128)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC6_X, IC6_Y, mload(add(pubSignals_, 160)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC7_X, IC7_Y, mload(add(pubSignals_, 192)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC8_X, IC8_Y, mload(add(pubSignals_, 224)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC9_X, IC9_Y, mload(add(pubSignals_, 256)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC10_X, IC10_Y, mload(add(pubSignals_, 288)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC11_X, IC11_Y, mload(add(pubSignals_, 320)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC12_X, IC12_Y, mload(add(pubSignals_, 352)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC13_X, IC13_Y, mload(add(pubSignals_, 384)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC14_X, IC14_Y, mload(add(pubSignals_, 416)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC15_X, IC15_Y, mload(add(pubSignals_, 448)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC16_X, IC16_Y, mload(add(pubSignals_, 480)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC17_X, IC17_Y, mload(add(pubSignals_, 512)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC18_X, IC18_Y, mload(add(pubSignals_, 544)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC19_X, IC19_Y, mload(add(pubSignals_, 576)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC20_X, IC20_Y, mload(add(pubSignals_, 608)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC21_X, IC21_Y, mload(add(pubSignals_, 640)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC22_X, IC22_Y, mload(add(pubSignals_, 672)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC23_X, IC23_Y, mload(add(pubSignals_, 704)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC24_X, IC24_Y, mload(add(pubSignals_, 736)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC25_X, IC25_Y, mload(add(pubSignals_, 768)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC26_X, IC26_Y, mload(add(pubSignals_, 800)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC27_X, IC27_Y, mload(add(pubSignals_, 832)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC28_X, IC28_Y, mload(add(pubSignals_, 864)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC29_X, IC29_Y, mload(add(pubSignals_, 896)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC30_X, IC30_Y, mload(add(pubSignals_, 928)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC31_X, IC31_Y, mload(add(pubSignals_, 960)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC32_X, IC32_Y, mload(add(pubSignals_, 992)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC33_X, IC33_Y, mload(add(pubSignals_, 1024)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC34_X, IC34_Y, mload(add(pubSignals_, 1056)))) {
                    leave
                }
                
                /// @dev -A
                mstore(pPairing_, mload(pA_))
                mstore(
                    add(pPairing_, 32),
                    mod(sub(BASE_FIELD_SIZE, mload(add(pA_, 32))), BASE_FIELD_SIZE)
                )

                /// @dev B
                mstore(add(pPairing_, 64), mload(mload(pB_)))
                mstore(add(pPairing_, 96), mload(add(mload(pB_), 32)))
                mstore(add(pPairing_, 128), mload(mload(add(pB_, 32))))
                mstore(add(pPairing_, 160), mload(add(mload(add(pB_, 32)), 32)))

                /// @dev alpha1
                mstore(add(pPairing_, 192), ALPHA_X)
                mstore(add(pPairing_, 224), ALPHA_Y)

                /// @dev beta2
                mstore(add(pPairing_, 256), BETA_X1)
                mstore(add(pPairing_, 288), BETA_X2)
                mstore(add(pPairing_, 320), BETA_Y1)
                mstore(add(pPairing_, 352), BETA_Y2)

                /// @dev public signals
                mstore(add(pPairing_, 384), mload(pointer_))
                mstore(add(pPairing_, 416), mload(add(pointer_, 32)))

                /// @dev gamma2
                mstore(add(pPairing_, 448), GAMMA_X1)
                mstore(add(pPairing_, 480), GAMMA_X2)
                mstore(add(pPairing_, 512), GAMMA_Y1)
                mstore(add(pPairing_, 544), GAMMA_Y2)

                /// @dev C
                mstore(add(pPairing_, 576), mload(pC_))
                mstore(add(pPairing_, 608), mload(add(pC_, 32)))

                /// @dev delta2
                mstore(add(pPairing_, 640), DELTA_X1)
                mstore(add(pPairing_, 672), DELTA_X2)
                mstore(add(pPairing_, 704), DELTA_Y1)
                mstore(add(pPairing_, 736), DELTA_Y2)

                res_ := staticcall(181000, 8, pPairing_, 768, pPairing_, 32) // ecPairing
                res_ := and(res_, mload(pPairing_)) // check that pairing succeeded
            }

            let pointer_ := mload(64) // free pointer
            mstore(64, add(pointer_, P_TOTAL_SIZE))

            /// @dev check that all public signals are in F
            verified_ := 1
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 0))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 32))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 64))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 96))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 128))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 160))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 192))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 224))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 256))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 288))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 320))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 352))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 384))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 416))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 448))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 480))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 512))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 544))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 576))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 608))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 640))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 672))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 704))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 736))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 768))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 800))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 832))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 864))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 896))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 928))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 960))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 992))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 1024))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 1056))))
            
            /// @dev check pairings
            if not(iszero(verified_)) {
                verified_ := checkPairing(pointA_, pointB_, pointC_, publicSignals_, pointer_)
            }
        }
    }
}
